triggers:
  - name: triggertest3
    type: trigger
    version:
      counter: 273
      
  - name: triggertest4
    type: trigger
    version:
      counter: 424

  - name: triggertest5
    type: trigger
    version:
      counter: 0
