triggers:
  - name: triggertestS1
    type: trigger
    version:
      counter: 3
      
  - name: triggertest4
    type: trigger
    version:
      counter: 427

  - name: triggertest5
    type: trigger
    version:
      counter: 0
