triggers:
  - name: triggertest3
    type: trigger
    version:
      counter: 274
      
  - name: triggertest4
    type: trigger
    version:
      counter: 42

  - name: triggertest5
    type: trigger
    version:
      counter: 0
